### PR TITLE
First Full Synchronization

### PR DESCRIPTION
**Pull request by esundbla**
Added Guest View path from home to navigate logic page.

### CODE REVIEW

**Review by SHamil36 — APPROVED** [review]

**Review by JoseWil-creator — APPROVED** [review]
Great job!

**Comment by esundbla** [comment]
Will be resolving backendtesting

**Review by FindingDorri — APPROVED** [review]
Looks great!

**Review by Brlan7 — COMMENTED** [review]
Tying everything up together. Great progress this week!

**Pull request merged**
